name: Build Ibiss PR

on:
  workflow_dispatch:
  pull_request:
      types:
        - closed
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm run actions:install

    - name: Build
      run: npm run build  # Replace this with the command to build your JavaScript files

    - name: Commit Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Build Ibiss"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
