name: Build Ibiss

on:
  pull_request:
      types:
        - closed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm run actions:install

    - name: Build
      run: npm run build  # Replace this with the command to build your JavaScript files

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Build Ibiss"
        git push origin master
